// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/content-item': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content-item').default>>>>
    }
    '/api/content': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content').default>>>>
    }
    '/api/content/debug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/debug').default>>>>
    }
    '/api/content/item': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/item.get').default>>>>
    }
    '/api/content/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/search').default>>>>
    }
    '/api/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search').default>>>>
    }
    '/.well-known/appspecific/com.chrome.devtools.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/.well-known/appspecific/com.chrome.devtools.json').default>>>>
    }
    '/well-known': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/well-known').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_1740375f8456d40c27ccdff16051e40c/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/:collection/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/:collection/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/_openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/routes/openapi').default>>>>
    }
    '/_scalar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/routes/scalar').default>>>>
    }
    '/_swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/routes/swagger').default>>>>
    }
  }
}
export {}