declare global {
  const __buildAssetsURL: typeof import('../../.pnpm-store/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_8a0cca195336401e66eaa2569f61a0cc/node_modules/nuxt/dist/core/runtime/nitro/utils/paths')['buildAssetsURL']
  const __publicAssetsURL: typeof import('../../.pnpm-store/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_8a0cca195336401e66eaa2569f61a0cc/node_modules/nuxt/dist/core/runtime/nitro/utils/paths')['publicAssetsURL']
  const appendCorsHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendCorsHeaders']
  const appendCorsPreflightHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendCorsPreflightHeaders']
  const appendHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendHeader']
  const appendHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendHeaders']
  const appendResponseHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendResponseHeader']
  const appendResponseHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['appendResponseHeaders']
  const assertMethod: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['assertMethod']
  const cachedEventHandler: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/cache')['cachedEventHandler']
  const cachedFunction: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/cache')['cachedFunction']
  const callNodeListener: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['callNodeListener']
  const clearResponseHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['clearResponseHeaders']
  const clearSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['clearSession']
  const createApp: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createApp']
  const createAppEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createAppEventHandler']
  const createError: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createError']
  const createEvent: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createEvent']
  const createEventStream: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createEventStream']
  const createRouter: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['createRouter']
  const defaultContentType: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defaultContentType']
  const defineAppConfig: typeof import('../../.pnpm-store/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_8a0cca195336401e66eaa2569f61a0cc/node_modules/nuxt/dist/core/runtime/nitro/utils/config')['defineAppConfig']
  const defineCachedEventHandler: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/cache')['defineCachedEventHandler']
  const defineCachedFunction: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/cache')['defineCachedFunction']
  const defineEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineEventHandler']
  const defineLazyEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineLazyEventHandler']
  const defineNitroErrorHandler: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/error/utils')['defineNitroErrorHandler']
  const defineNitroPlugin: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/plugin')['defineNitroPlugin']
  const defineNodeListener: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineNodeListener']
  const defineNodeMiddleware: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineNodeMiddleware']
  const defineRenderHandler: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/renderer')['defineRenderHandler']
  const defineRequestMiddleware: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineRequestMiddleware']
  const defineResponseMiddleware: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineResponseMiddleware']
  const defineRouteMeta: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/meta')['defineRouteMeta']
  const defineTask: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/task')['defineTask']
  const defineWebSocket: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineWebSocket']
  const defineWebSocketHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['defineWebSocketHandler']
  const deleteCookie: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['deleteCookie']
  const dynamicEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['dynamicEventHandler']
  const eventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['eventHandler']
  const fetchWithEvent: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['fetchWithEvent']
  const fromNodeMiddleware: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['fromNodeMiddleware']
  const fromPlainHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['fromPlainHandler']
  const fromWebHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['fromWebHandler']
  const getCookie: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getCookie']
  const getHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getHeader']
  const getHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getHeaders']
  const getMethod: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getMethod']
  const getProxyRequestHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getProxyRequestHeaders']
  const getQuery: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getQuery']
  const getRequestFingerprint: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestFingerprint']
  const getRequestHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestHeader']
  const getRequestHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestHeaders']
  const getRequestHost: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestHost']
  const getRequestIP: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestIP']
  const getRequestPath: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestPath']
  const getRequestProtocol: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestProtocol']
  const getRequestURL: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestURL']
  const getRequestWebStream: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRequestWebStream']
  const getResponseHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getResponseHeader']
  const getResponseHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getResponseHeaders']
  const getResponseStatus: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getResponseStatus']
  const getResponseStatusText: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getResponseStatusText']
  const getRouteRules: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/route-rules')['getRouteRules']
  const getRouterParam: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRouterParam']
  const getRouterParams: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getRouterParams']
  const getSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getSession']
  const getValidatedQuery: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getValidatedQuery']
  const getValidatedRouterParams: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['getValidatedRouterParams']
  const handleCacheHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['handleCacheHeaders']
  const handleCors: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['handleCors']
  const isCorsOriginAllowed: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isCorsOriginAllowed']
  const isError: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isError']
  const isEvent: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isEvent']
  const isEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isEventHandler']
  const isMethod: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isMethod']
  const isPreflightRequest: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isPreflightRequest']
  const isStream: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isStream']
  const isWebResponse: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['isWebResponse']
  const lazyEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['lazyEventHandler']
  const nitroPlugin: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/plugin')['nitroPlugin']
  const parseCookies: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['parseCookies']
  const parseMarkdown: typeof import('../../.pnpm-store/@nuxtjs+mdc@0.17.0_magicast@0.3.5/node_modules/@nuxtjs/mdc/dist/runtime/parser')['parseMarkdown']
  const promisifyNodeListener: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['promisifyNodeListener']
  const proxyRequest: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['proxyRequest']
  const queryCollection: typeof import('../../.pnpm-store/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/nitro')['queryCollection']
  const queryCollectionItemSurroundings: typeof import('../../.pnpm-store/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/nitro')['queryCollectionItemSurroundings']
  const queryCollectionNavigation: typeof import('../../.pnpm-store/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/nitro')['queryCollectionNavigation']
  const queryCollectionSearchSections: typeof import('../../.pnpm-store/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/nitro')['queryCollectionSearchSections']
  const readBody: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['readBody']
  const readFormData: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['readFormData']
  const readMultipartFormData: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['readMultipartFormData']
  const readRawBody: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['readRawBody']
  const readValidatedBody: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['readValidatedBody']
  const removeResponseHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['removeResponseHeader']
  const runTask: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/task')['runTask']
  const sanitizeStatusCode: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sanitizeStatusCode']
  const sanitizeStatusMessage: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sanitizeStatusMessage']
  const sealSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sealSession']
  const send: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['send']
  const sendError: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendError']
  const sendIterable: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendIterable']
  const sendNoContent: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendNoContent']
  const sendProxy: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendProxy']
  const sendRedirect: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendRedirect']
  const sendStream: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendStream']
  const sendWebResponse: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['sendWebResponse']
  const serveStatic: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['serveStatic']
  const setCookie: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setCookie']
  const setHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setHeader']
  const setHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setHeaders']
  const setResponseHeader: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setResponseHeader']
  const setResponseHeaders: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setResponseHeaders']
  const setResponseStatus: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['setResponseStatus']
  const splitCookiesString: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['splitCookiesString']
  const stringifyMarkdown: typeof import('../../.pnpm-store/@nuxtjs+mdc@0.17.0_magicast@0.3.5/node_modules/@nuxtjs/mdc/dist/runtime/stringify')['stringifyMarkdown']
  const toEventHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['toEventHandler']
  const toNodeListener: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['toNodeListener']
  const toPlainHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['toPlainHandler']
  const toWebHandler: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['toWebHandler']
  const toWebRequest: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['toWebRequest']
  const unsealSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['unsealSession']
  const updateSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['updateSession']
  const useAppConfig: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/config')['useAppConfig']
  const useBase: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['useBase']
  const useEvent: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/context')['useEvent']
  const useNitroApp: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/app')['useNitroApp']
  const useRuntimeConfig: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/config')['useRuntimeConfig']
  const useSession: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['useSession']
  const useStorage: typeof import('../../.pnpm-store/nitropack@2.11.13_better-sqlite3@12.1.1/node_modules/nitropack/dist/runtime/internal/storage')['useStorage']
  const writeEarlyHints: typeof import('../../.pnpm-store/h3@1.15.3/node_modules/h3')['writeEarlyHints']
}
export { useNitroApp } from 'nitropack/runtime/internal/app';
export { useRuntimeConfig, useAppConfig } from 'nitropack/runtime/internal/config';
export { defineNitroPlugin, nitroPlugin } from 'nitropack/runtime/internal/plugin';
export { defineCachedFunction, defineCachedEventHandler, cachedFunction, cachedEventHandler } from 'nitropack/runtime/internal/cache';
export { useStorage } from 'nitropack/runtime/internal/storage';
export { defineRenderHandler } from 'nitropack/runtime/internal/renderer';
export { defineRouteMeta } from 'nitropack/runtime/internal/meta';
export { getRouteRules } from 'nitropack/runtime/internal/route-rules';
export { useEvent } from 'nitropack/runtime/internal/context';
export { defineTask, runTask } from 'nitropack/runtime/internal/task';
export { defineNitroErrorHandler } from 'nitropack/runtime/internal/error/utils';
export { appendCorsHeaders, appendCorsPreflightHeaders, appendHeader, appendHeaders, appendResponseHeader, appendResponseHeaders, assertMethod, callNodeListener, clearResponseHeaders, clearSession, createApp, createAppEventHandler, createError, createEvent, createEventStream, createRouter, defaultContentType, defineEventHandler, defineLazyEventHandler, defineNodeListener, defineNodeMiddleware, defineRequestMiddleware, defineResponseMiddleware, defineWebSocket, defineWebSocketHandler, deleteCookie, dynamicEventHandler, eventHandler, fetchWithEvent, fromNodeMiddleware, fromPlainHandler, fromWebHandler, getCookie, getHeader, getHeaders, getMethod, getProxyRequestHeaders, getQuery, getRequestFingerprint, getRequestHeader, getRequestHeaders, getRequestHost, getRequestIP, getRequestPath, getRequestProtocol, getRequestURL, getRequestWebStream, getResponseHeader, getResponseHeaders, getResponseStatus, getResponseStatusText, getRouterParam, getRouterParams, getSession, getValidatedQuery, getValidatedRouterParams, handleCacheHeaders, handleCors, isCorsOriginAllowed, isError, isEvent, isEventHandler, isMethod, isPreflightRequest, isStream, isWebResponse, lazyEventHandler, parseCookies, promisifyNodeListener, proxyRequest, readBody, readFormData, readMultipartFormData, readRawBody, readValidatedBody, removeResponseHeader, sanitizeStatusCode, sanitizeStatusMessage, sealSession, send, sendError, sendIterable, sendNoContent, sendProxy, sendRedirect, sendStream, sendWebResponse, serveStatic, setCookie, setHeader, setHeaders, setResponseHeader, setResponseHeaders, setResponseStatus, splitCookiesString, toEventHandler, toNodeListener, toPlainHandler, toWebHandler, toWebRequest, unsealSession, updateSession, useBase, useSession, writeEarlyHints } from 'h3';
export { buildAssetsURL as __buildAssetsURL, publicAssetsURL as __publicAssetsURL } from '/Users/drew/Documents/_work/WakeUpNPC2/.pnpm-store/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_8a0cca195336401e66eaa2569f61a0cc/node_modules/nuxt/dist/core/runtime/nitro/utils/paths';
export { defineAppConfig } from '/Users/drew/Documents/_work/WakeUpNPC2/.pnpm-store/nuxt@3.17.5_@parcel+watcher@2.5.1_@types+node@24.0.4_better-sqlite3@12.1.1_db0@0.3.2_be_8a0cca195336401e66eaa2569f61a0cc/node_modules/nuxt/dist/core/runtime/nitro/utils/config';
export { queryCollection, queryCollectionSearchSections, queryCollectionNavigation, queryCollectionItemSurroundings } from '/Users/drew/Documents/_work/WakeUpNPC2/.pnpm-store/@nuxt+content@3.6.1_better-sqlite3@12.1.1_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/nitro';
export { parseMarkdown } from '/Users/drew/Documents/_work/WakeUpNPC2/.pnpm-store/@nuxtjs+mdc@0.17.0_magicast@0.3.5/node_modules/@nuxtjs/mdc/dist/runtime/parser';
export { stringifyMarkdown } from '/Users/drew/Documents/_work/WakeUpNPC2/.pnpm-store/@nuxtjs+mdc@0.17.0_magicast@0.3.5/node_modules/@nuxtjs/mdc/dist/runtime/stringify';