# netlify.toml

[build]
command = "pnpm run generate"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.8"
PNPM_FLAGS = "--shamefully-hoist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200