// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/25/2025, 6:52:47 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/drew/Documents/_work/WakeUpNPC2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/plugins/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/composables/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/utils/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/app.config.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;