// Server API endpoint for ads
// Returns ad data from generated JSON (public/content-ads.json)
// This keeps ads in sync with content/ads/*.md and avoids having to hardcode paths.

import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export default defineEventHandler(async () => {
  try {
    // content-ads.json is generated by scripts/regenerate-content-json.js
    // and committed/deployed as a static asset under /public.
    // IMPORTANT (Netlify): during serverless runtime, process.cwd() is not
    // guaranteed to include the full repo with /public. However, the generated
    // JSON is always accessible as a deployed static file at /content-ads.json.
    // So we fetch it via $fetch from the local server runtime.
    const raw = await $fetch('/content-ads.json', { responseType: 'text' })
    const adsData = JSON.parse(String(raw))

    if (!Array.isArray(adsData)) {
      console.warn('⚠️ Invalid ads data (not an array)')
      return { data: [] }
    }

    // Filter only active ads
    const activeAds = adsData.filter((ad) => ad && ad.active !== false)

    if (import.meta.dev) {
      console.log(`✅ Loaded ${activeAds.length} active ads`)
      console.log(
        'Ad IDs:',
        activeAds.map((ad) => ad.id)
      )
    }

    return { data: activeAds }
  } catch (error) {
    console.error('❌ Error loading ads:', error)
    // Return empty array instead of failing
    return { data: [] }
  }
})
