// Server API endpoint for ads
// Returns ad data from generated JSON (public/content-ads.json)
// This keeps ads in sync with content/ads/*.md and avoids having to hardcode paths.

import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export default defineEventHandler(async () => {
  try {
    // content-ads.json is generated by scripts/regenerate-content-json.js
    // and committed/deployed as a static asset under /public.
    const adsJsonPath = join(process.cwd(), 'public', 'content-ads.json')
    const raw = await readFile(adsJsonPath, 'utf8')
    const adsData = JSON.parse(raw)

    if (!Array.isArray(adsData)) {
      console.warn('⚠️ Invalid ads data (not an array)')
      return { data: [] }
    }

    // Filter only active ads
    const activeAds = adsData.filter((ad) => ad && ad.active !== false)

    if (import.meta.dev) {
      console.log(`✅ Loaded ${activeAds.length} active ads`)
      console.log(
        'Ad IDs:',
        activeAds.map((ad) => ad.id)
      )
    }

    return { data: activeAds }
  } catch (error) {
    console.error('❌ Error loading ads:', error)
    // Return empty array instead of failing
    return { data: [] }
  }
})
