// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2025, 1:52:58 PM
const configMerger = require("/Users/drew/Documents/_work/wake-up-npc/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/drew/Documents/_work/wake-up-npc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/plugins/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/wake-up-npc/composables/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/wake-up-npc/utils/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/wake-up-npc/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/wake-up-npc/app.config.{js,ts,mjs}"] }));

module.exports = config
