// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2025, 2:33:40 PM
const configMerger = require("/Users/drew/Documents/_work/WakeUpNPC2/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/drew/Documents/_work/WakeUpNPC2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/plugins/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/composables/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/utils/**/*.{js,ts,mjs}","/Users/drew/Documents/_work/WakeUpNPC2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/drew/Documents/_work/WakeUpNPC2/app.config.{js,ts,mjs}"] }));

module.exports = config
