import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ClaimsCollectionItem extends PageCollectionItemBase {}
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface QuotesCollectionItem extends PageCollectionItemBase {}
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface MemesCollectionItem extends PageCollectionItemBase {}
  

  interface PageCollections {
    claims: ClaimsCollectionItem
    quotes: QuotesCollectionItem
    memes: MemesCollectionItem
  }

  interface Collections {
    claims: ClaimsCollectionItem
    quotes: QuotesCollectionItem
    memes: MemesCollectionItem
  }
}
